version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
  build:
    commands:
      - npm run build
      # Copiar los archivos necesarios dentro de build para que queden empaquetados juntos
      - cp ../appspec.yml ./          # Copia appspec.yml dentro de build/
      - cp ../install.sh ./           # Copia install.sh dentro de build/
      - cp ../start.sh ./             # Copia start.sh dentro de build/

artifacts:
  base-directory: build
  files:
    - '**/*'
