version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
  build:
    commands:
      - npm run build
      - cp appspec.yml build/
      - cp install.sh build/
      - cp start.sh build/
      - ls -la build/

artifacts:
  files:
    - "**/*"
  base-directory: build
